import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Waterlily Take Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hi there if you'd like to start the survey feel free to click the link below.
        <Link href="/survey">Go to Survey</Link>
      </main>
    </>
  );
}
